# Generated by Django 5.2 on 2025-04-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('hash', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('size', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('download_finished', models.BooleanField()),
                ('download_present', models.BooleanField()),
                ('tracker', models.TextField()),
                ('total_uploaded', models.IntegerField()),
                ('total_downloaded', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TorrentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('short_name', models.TextField()),
                ('size', models.IntegerField()),
                ('hash', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrent')),
            ],
        ),
        migrations.CreateModel(
            name='TorrentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.IntegerField()),
                ('upload_speed', models.IntegerField()),
                ('eta', models.IntegerField()),
                ('peers', models.IntegerField()),
                ('ratio', models.FloatField()),
                ('seeds', models.IntegerField()),
                ('progress', models.FloatField()),
                ('updated_at', models.DateTimeField()),
                ('availability', models.FloatField()),
                ('state', models.TextField()),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrent')),
            ],
        ),
    ]
