# Generated by Django 5.2 on 2025-04-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='client',
            field=models.CharField(default='TorBox', max_length=50),
        ),
        migrations.AddField(
            model_name='torrent',
            name='internal_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='torrentfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='torrentfile',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
