# Generated by Django 5.2 on 2025-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0002_torrent_client_torrent_internal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrenthistory',
            name='eta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
