# Generated by Django 5.2 on 2025-04-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0003_alter_torrenthistory_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentfile',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
