# Generated by Django 5.2 on 2025-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0004_alter_torrentfile_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
