# Generated by Django 5.2 on 2025-04-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0005_torrent_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentfile',
            name='internal_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
