# Generated by Django 5.2 on 2025-04-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0006_torrentfile_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='tracker',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
