# Generated by Django 5.2 on 2025-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0007_alter_torrent_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentfile',
            name='aria_internal_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
