# Generated by Django 5.2 on 2025-05-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0008_torrentfile_aria_internal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentTorBoxSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('cached', models.BooleanField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TorrentTorBoxSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=255)),
                ('raw_title', models.TextField()),
                ('resolution', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('codec', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('magnet', models.TextField()),
                ('age', models.CharField(max_length=10)),
                ('cached', models.BooleanField()),
                ('last_known_seeders', models.IntegerField()),
                ('last_known_peers', models.IntegerField()),
                ('size', models.IntegerField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrenttorboxsearch')),
            ],
        ),
    ]
