# Generated by Django 5.2 on 2025-05-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0009_torrenttorboxsearch_torrenttorboxsearchresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrenttorboxsearch',
            name='cached',
        ),
    ]
