# Generated by Django 5.2 on 2025-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0010_remove_torrenttorboxsearch_cached'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='magnet',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
