# Generated by Django 5.2 on 2025-05-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0011_torrent_magnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='doubled',
            field=models.BooleanField(default=False),
        ),
    ]
