# Generated by Django 5.2 on 2025-05-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0012_torrent_doubled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AriaDownloadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aria_internal_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('path', models.CharField(max_length=255)),
                ('progress', models.FloatField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='torrentfile',
            name='aria_internal_id',
        ),
        migrations.AddField(
            model_name='torrent',
            name='local_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torrent',
            name='local_download_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torrentfile',
            name='aria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tor.ariadownloadstatus'),
        ),
    ]
