# Generated by Django 5.2 on 2025-05-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0013_ariadownloadstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ariadownloadstatus',
            old_name='aria_internal_id',
            new_name='internal_id',
        ),
    ]
