# Generated by Django 5.2 on 2025-05-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0014_rename_aria_internal_id_ariadownloadstatus_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='local_download_progress',
            field=models.FloatField(default=0),
        ),
    ]
