# Generated by Django 5.2 on 2025-05-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0015_torrent_local_download_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='redownload',
            field=models.BooleanField(default=False),
        ),
    ]
