# Generated by Django 5.2 on 2025-05-25 10:25

import django.db.models.deletion
from django.db import migrations, models

def fill_initial_types(apps, schema_editor):
    TorrentType = apps.get_model('tor', 'TorrentType')
    TorrentType.objects.create(name='Movies')
    TorrentType.objects.create(name='Movie Series')
    TorrentType.objects.create(name='Audiobooks')
    TorrentType.objects.create(name='E-Books')


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0016_torrent_redownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('copy_on_finish', models.BooleanField(default=False)),
                ('move_on_finish', models.BooleanField(default=False)),
                ('target_dir', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='torrent',
            name='torrent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tor.torrenttype'),
        ),
        migrations.RunPython(fill_initial_types)
    ]
