# Generated by Django 5.2 on 2025-05-25 13:50

import django.db.models.deletion
from django.db import migrations, models

def fill_empty_type(apps, schema_editor):
    TorrentType = apps.get_model('tor', 'TorrentType')
    no_type = TorrentType.objects.create(name='No Type')
    Torrent = apps.get_model('tor', 'Torrent')
    Torrent.objects.filter(torrent_type__isnull=True).update(torrent_type=no_type)


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0017_torrenttype_torrent_torrent_type'),
    ]

    operations = [
        migrations.RunPython(fill_empty_type),
        migrations.AlterField(
            model_name='torrent',
            name='torrent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrenttype'),
        ),
    ]
