# Generated by Django 5.2 on 2025-06-01 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0018_alter_torrent_torrent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrenttorboxsearchresult',
            name='episode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='torrenttorboxsearchresult',
            name='episode_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='torrenttorboxsearchresult',
            name='season',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='torrenttorboxsearchresult',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='torrenttorboxsearchresult',
            name='torrent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.torrent'),
        ),
    ]
