# Generated by Django 5.2 on 2025-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0019_torrenttorboxsearchresult_episode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrenttype',
            name='copy_on_finish',
        ),
        migrations.RemoveField(
            model_name='torrenttype',
            name='move_on_finish',
        ),
        migrations.AddField(
            model_name='torrenttype',
            name='action_on_finish',
            field=models.CharField(default='Nothing', max_length=50),
        ),
    ]
