# Generated by Django 5.2 on 2025-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0020_remove_torrenttype_copy_on_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='ERROR', max_length=50)),
                ('source', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
