# Generated by Django 5.2 on 2025-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0021_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentfile',
            name='action_on_finish_done',
            field=models.BooleanField(default=False),
        ),
    ]
