# Generated by Django 5.2 on 2025-07-26 13:04

from django.db import migrations


def fill_default_folders(apps, schema_editor):
    TorrentType = apps.get_model('tor', 'TorrentType')
    movies = TorrentType.objects.get(name='Movies')
    movies.action_on_finish = 'Move'
    movies.target_dir = '/data/movies'
    movies.save()
    series = TorrentType.objects.get(name='Movie Series')
    series.action_on_finish = 'Move'
    series.target_dir = '/data/movie_series'
    series.save()
    audio = TorrentType.objects.get(name='Audiobooks')
    audio.action_on_finish = 'Move'
    audio.target_dir = '/data/audio'
    audio.save()
    books = TorrentType.objects.get(name='E-Books')
    books.action_on_finish = 'Move'
    books.target_dir = '/data/books'
    books.save()
    home = TorrentType.objects.create(name='Home Videos', 
                                      action_on_finish='Move',
                                      target_dir='/data/home')
    other = TorrentType.objects.create(name='Other', 
                                      action_on_finish='Move',
                                      target_dir='/data/other')
    

class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0022_torrentfile_action_on_finish_done'),
    ]

    operations = [
        migrations.RunPython(fill_default_folders),        
    ]
