# Generated by Django 5.2.4 on 2025-08-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0023_default_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='torrent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tor.torrent'),
        ),
    ]
