# Generated by Django 5.2.4 on 2025-08-03 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0024_errorlog_torrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='torrent',
        ),
        migrations.CreateModel(
            name='TorrentErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.errorlog')),
                ('torrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrent')),
            ],
        ),
    ]
