# Generated by Django 5.2.4 on 2025-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0025_remove_errorlog_torrent_torrenterrorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='download_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='download_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='name',
            field=models.TextField(default='Empty Torrent'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='total_downloaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='total_uploaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='availability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='download_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='peers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='seeds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='state',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='torrenthistory',
            name='upload_speed',
            field=models.IntegerField(default=0),
        ),
    ]
