# Generated by Django 5.2.4 on 2025-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0026_alter_torrent_download_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='local_status',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='torrent',
            name='local_status_level',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
