# Generated by Django 5.2.4 on 2025-08-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0028_level_ariadownloadstatus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.level'),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='local_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrentstatus'),
        ),
    ]
