# Generated by Django 5.2.4 on 2025-08-17 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tor", "0029_alter_errorlog_level_alter_torrent_local_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TorrentQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("magnet", models.TextField(blank=True, default=None, null=True)),
                ("torrent_file", models.BinaryField(default=None, null=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "torrent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tor.torrenttype",
                    ),
                ),
            ],
        ),
    ]
