# Generated by Django 5.2.4 on 2025-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0030_torrentqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='cached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torrent',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
