# Generated by Django 5.2.4 on 2025-08-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0031_torrent_cached_torrent_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentqueue',
            name='torrent_file_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='name',
            field=models.TextField(default='Placeholder Torrent'),
        ),
    ]
