# Generated by Django 5.2.4 on 2025-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0032_torrentqueue_torrent_file_name_alter_torrent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentqueue',
            name='torrent_private',
            field=models.BooleanField(default=False),
        ),
    ]
