# Generated by Django 5.2.4 on 2025-08-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0033_torrentqueue_torrent_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrenttorboxsearchresult',
            name='hash',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
