# Generated by Django 5.2.4 on 2025-09-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tor", "0034_alter_torrenttorboxsearchresult_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArrBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_checked",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "include_words",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "exclude_words",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "last_added_torrent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arr_last_added",
                        to="tor.torrent",
                    ),
                ),
                (
                    "torrent_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tor.torrenttype",
                    ),
                ),
                (
                    "last_found",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArrMovieSeries",
            fields=[
                (
                    "arrbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tor.arrbase",
                    ),
                ),
                ("imdbid", models.CharField(max_length=20)),
                (
                    "quality",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "encoder",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("requested_episode", models.IntegerField()),
                ("requested_season", models.IntegerField()),
                (
                    "title",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
            ],
            bases=("tor.arrbase",),
        ),
    ]
