# Generated by Django 5.2.4 on 2025-09-14 09:08

import django.db.models.deletion
from django.db import migrations, models


def fill_default_arr(apps, schema_editor):
    ArrMovieSeries = apps.get_model("tor", "ArrMovieSeries")
    TorrentType = apps.get_model("tor", "TorrentType")
    movie_series = TorrentType.objects.get(name="Movie Series")
    ArrMovieSeries.objects.create(
        active=False,
        torrent_type=movie_series,
        imdbid="DEFAULT",
        requested_season=1,
        requested_episode=1,
        quality="ANY",
        encoder="ANY",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tor", "0035_arrbase_arrmovieseries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arrbase",
            name="last_added_torrent",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arr_last_added",
                to="tor.torrent",
            ),
        ),
        migrations.AlterField(
            model_name="arrmovieseries",
            name="imdbid",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="torrenttorboxsearchresult",
            name="episode",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ArrErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tor.arrbase"
                    ),
                ),
                (
                    "error_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tor.errorlog"
                    ),
                ),
            ],
        ),
        migrations.RunPython(fill_default_arr),
    ]
