# Generated by Django 5.2.4 on 2025-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0036_alter_arrbase_last_added_torrent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrenttorboxsearch',
            name='episode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='torrenttorboxsearch',
            name='season',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
