# Generated by Django 5.2.4 on 2025-09-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0037_torrenttorboxsearch_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrenttorboxsearchresult',
            name='queue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.torrentqueue'),
        ),
    ]
