# Generated by Django 5.2.4 on 2025-09-20 09:01

import django.db.models.deletion
from django.db import migrations, models


def fill_sources(apps, schema_editor):
    LogSource = apps.get_model("tor", "LogSource")
    LogSource.objects.create(name="torboxapi")
    LogSource.objects.create(name="action")
    LogSource.objects.create(name="actionmgr")
    LogSource.objects.create(name="ariaapi")
    LogSource.objects.create(name="statusmgr")
    LogSource.objects.create(name="queuemgr")
    LogSource.objects.create(name="arrmanager")
    LogSource.objects.create(name="transmissionapi")

    ErrorLog = apps.get_model("tor", "ErrorLog")
    for log in ErrorLog.objects.all():
        key = LogSource.objects.get(name=log.source)
        log.source_key = key
        log.save()


class Migration(migrations.Migration):

    dependencies = [
        ("tor", "0038_torrenttorboxsearchresult_queue"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="errorlog",
            name="source_key",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tor.logsource",
            ),
        ),
        migrations.RunPython(fill_sources),
        migrations.RemoveField(
            model_name="errorlog",
            name="source",
        ),
        migrations.RenameField(
            model_name="errorlog",
            old_name="source_key",
            new_name="source",
        ),
    ]
