# Generated by Django 5.2.4 on 2025-09-21 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0039_logsource_alter_errorlog_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrbase',
            name='last_added_torrent',
        ),
        migrations.AddField(
            model_name='torrent',
            name='arr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.arrbase'),
        ),
    ]
