# Generated by Django 5.2.4 on 2025-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0040_remove_arrbase_last_added_torrent_torrent_arr'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrmovieseries',
            name='skip_full_season',
            field=models.BooleanField(default=False),
        ),
    ]
