# Generated by Django 5.2.4 on 2026-01-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0041_arrmovieseries_skip_full_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='JackettSearchResultBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('torrent_link', models.TextField()),
                ('size', models.IntegerField()),
                ('grabs', models.IntegerField()),
                ('seeders', models.IntegerField()),
                ('peers', models.IntegerField()),
                ('indexer', models.CharField(max_length=255)),
                ('private', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('comments', models.TextField(blank=True, default=None, null=True)),
                ('guid', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hash', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('torbox_cached', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JackettSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('torrent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrenttype')),
            ],
        ),
        migrations.CreateModel(
            name='JackettSearchResultHomeVideo',
            fields=[
                ('jackettsearchresultbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tor.jackettsearchresultbase')),
                ('performer', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            bases=('tor.jackettsearchresultbase',),
        ),
        migrations.CreateModel(
            name='JakettSearchResultAudiobook',
            fields=[
                ('jackettsearchresultbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tor.jackettsearchresultbase')),
                ('author', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('narrator', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            bases=('tor.jackettsearchresultbase',),
        ),
        migrations.AddField(
            model_name='jackettsearchresultbase',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.jackettsearch'),
        ),
        migrations.AddField(
            model_name='jackettsearchresultbase',
            name='queue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.torrentqueue'),
        ),
        migrations.AddField(
            model_name='jackettsearchresultbase',
            name='torrent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tor.torrent'),
        ),
        migrations.CreateModel(
            name='JakettQueryUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('torrent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrenttype')),
            ],
        ),
    ]
