# Generated by Django 5.2.4 on 2026-01-01 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0042_jackettsearchresultbase_jackettsearch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('progress', models.FloatField(default=0.0)),
                ('downloaded', models.BigIntegerField(default=0)),
                ('uploaded', models.BigIntegerField(default=0)),
                ('client_is_choked', models.BooleanField(default=False)),
                ('client_is_interested', models.BooleanField(default=False)),
                ('peer_is_choked', models.BooleanField(default=False)),
                ('peer_is_interested', models.BooleanField(default=False)),
                ('flags', models.CharField(blank=True, max_length=255, null=True)),
                ('torrent_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tor.torrenthistory')),
            ],
        ),
    ]
