# Generated by Django 5.2.4 on 2026-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0043_torrentpeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackettsearchresultbase',
            name='magnet_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
