# Generated by Django 5.2.4 on 2026-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0044_jackettsearchresultbase_magnet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentpeer',
            name='is_incoming',
            field=models.BooleanField(default=False),
        ),
    ]
