# Generated by Django 5.2.4 on 2026-01-14 15:34

from django.db import migrations


def fill_empty_jackett_config(apps, schema_editor):
    JakettQueryUrl = apps.get_model("tor", "JakettQueryUrl")
    TorrentType = apps.get_model("tor", "TorrentType")
    for type in TorrentType.objects.all():
        JakettQueryUrl.objects.get_or_create(
            torrent_type=type,
            defaults={"name": f"Default Jackett RSS for {type.name}", "url": ""},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tor", "0045_torrentpeer_is_incoming"),
    ]

    operations = [
        migrations.RunPython(fill_empty_jackett_config),
    ]
