# Generated by Django 5.2.4 on 2026-01-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0046_empty_jackett_config'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JakettQueryUrl',
            new_name='JackettQueryUrl',
        ),
        migrations.RenameModel(
            old_name='JakettSearchResultAudiobook',
            new_name='JackettSearchResultAudiobook',
        ),
    ]
