# Generated by Django 5.2.4 on 2026-01-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0047_rename_jakettqueryurl_jackettqueryurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackettsearchresultbase',
            name='torbox_cached_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
