# Generated by Django 5.2.4 on 2026-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0048_jackettsearchresultbase_torbox_cached_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackettsearchresultbase',
            name='guid',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jackettsearchresultbase',
            name='hash',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
