# Generated by Django 5.2.4 on 2026-01-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0049_alter_jackettsearchresultbase_guid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackettsearchresulthomevideo',
            name='tags',
        ),
        migrations.AddField(
            model_name='jackettsearchresultaudiobook',
            name='cover_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='jackettsearchresultbase',
            name='tags',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
