# Generated by Django 5.2.4 on 2026-01-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0050_remove_jackettsearchresulthomevideo_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='hash',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
