# Generated by Django 6.0.3 on 2026-03-22 09:10

from django.db import migrations, models


def copy_titles(apps, schema_editor):
    JackettSearchResultBase = apps.get_model("tor", "JackettSearchResultBase")
    JackettSearchResultBase.objects.update(full_title=models.F("title"))


class Migration(migrations.Migration):

    dependencies = [
        ("tor", "0052_person_jackettsearchresultaudiobook_part_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_titles),
    ]
