# Generated by Django 6.0.3 on 2026-03-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tor', '0053_auto_20260322_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackettsearchresultbase',
            name='full_title',
            field=models.CharField(max_length=255),
        ),
    ]
