# docker-compose.yml
volumes:
  persistent_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/persistent_data # <--- Specify your host path here, it will be used for persistent data, configurations, logs
  aria_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/aria2 # <--- Specify your aria2 host path here
  movies_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/movies/ # <--- Specify your movies host path here
  movie_series_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/movie_series/ # <--- Specify your movie series host path here
  books_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/books/ # <--- Specify your books host path here
  audio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/audiobooks/ # <--- Specify your audio host path here
  other_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/other/ # <--- Specify your other host path here
  home_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/home/ # <--- Specify your home videos host path here
services:  
  yatbc-prepare:    
    image: yatbc/yatbc:gui-latest
    container_name: yatbc-prepare
    user: "1000:1000" # Run as non-root user (adjust UID:GID as needed)
    
    volumes:
      - persistent_data:/data/persistent
      - aria_data:/data/aria2
      - movies_data:/data/movies
      - movie_series_data:/data/movie_series
      - books_data:/data/books
      - audio_data:/data/audio
      - other_data:/data/other
      - home_data:/data/home
    restart: no # This service is only run once to prepare the environment
    environment:
      - TZ=Europe/Warsaw # Adjust timezone

    command: >
      /bin/bash /var/www/yatbc/prepare.sh

  yatbc-gui:
    image: yatbc/yatbc:gui-latest
    container_name: yatbc-gui    
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "7097:80"
    user: "1000:1000" # Run as non-root user (adjust UID:GID as needed)

    volumes:
      - persistent_data:/data/persistent
      - aria_data:/data/aria2
      - movies_data:/data/movies
      - movie_series_data:/data/movie_series
      - books_data:/data/books
      - audio_data:/data/audio
      - other_data:/data/other
      - home_data:/data/home
    
    restart: unless-stopped

    depends_on:
      yatbc-prepare: 
        condition: service_completed_successfully 
  yatbc-worker:
    image: yatbc/yatbc:worker-latest
    container_name: yatbc-worker    
    depends_on:
      - yatbc-gui    
    user: "1000:1000" # Run as non-root user (adjust UID:GID as needed)
    environment:
      - TZ=Europe/Warsaw # Adjust timezone
    volumes:
      - persistent_data:/data/persistent
      - aria_data:/data/aria2
      - movies_data:/data/movies
      - movie_series_data:/data/movie_series
      - books_data:/data/books
      - audio_data:/data/audio
      - other_data:/data/other
      - home_data:/data/home
    
    restart: unless-stopped
  yatbc-aria:
    image: yatbc/yatbc:aria-latest
    depends_on:
      - yatbc-gui
    ports:
      - "6800:6800" 
    
    user: "1000:1000" # Run as non-root user (adjust UID:GID as needed)
    environment:
      - TZ=Europe/Warsaw # Adjust timezone

    volumes:
      - persistent_data:/data/persistent
      - aria_data:/data/aria2
      - movies_data:/data/movies
      - movie_series_data:/data/movie_series
      - books_data:/data/books
      - audio_data:/data/audio
      - other_data:/data/other
      - home_data:/data/home
    
    restart: unless-stopped
