FROM httpd:2.4

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    libapache2-mod-wsgi-py3 \
    python3-venv \
    python3-pip \
    dnsutils \
    tzdata 
COPY docker/yatbc-gui/my-httpd.conf /usr/local/apache2/conf/httpd.conf
COPY ./yatbc /var/www/yatbc
COPY docker/yatbc-prepare/prepare.sh /var/www/yatbc
COPY docker/aria/aria2.conf /etc/aria2.conf

RUN groupadd -g 1000 yatbc
RUN useradd -u 1000 -g 1000 -G www-data yatbc
RUN mkdir -p /var/www/yatbc/wsgi && \
    chown -R yatbc:yatbc /var/www/yatbc && \
    chmod -R 755 /var/www/yatbc 

RUN python3 -m venv /var/venv_django && \
    . /var/venv_django/bin/activate && \
    pip install --upgrade pip && \
    pip install -r /var/www/yatbc/requirements.txt && \    
    deactivate

USER yatbc